import 'package:easy_localization/easy_localization.dart';

class SubtitleLanguage {
  List<String> supportedLanguages = [
    '',
    tr("arabic"),
    tr("bulgarian"),
    tr("chinese"),
    tr("croaitian"),
    tr("czech"),
    tr("danish"),
    tr("dutch"),
    tr("english"),
    tr("estonian"),
    tr("finnish"),
    tr("french"),
    tr("german"),
    tr("greek"),
    tr("hebrew"),
    tr("hindi"),
    tr("hungarian"),
    tr("indonesian"),
    tr("italian"),
    tr("japanese"),
    tr("korean"),
    tr("latvian"),
    tr("lithuanian"),
    tr("malay"),
    tr("norwegian"),
    tr("polish"),
    tr("portuguese"),
    tr("romanian"),
    tr("russian"),
    tr("slovak"),
    tr("slovene"),
    tr("spanish"),
    tr("swedish"),
    tr("thai"),
    tr("turkish"),
    tr("ukrainian")
  ];
}
