import 'package:easy_localization/easy_localization.dart';

class SubtitleLanguage {
  List<String> supportedLanguages = [
    '',
    tr("arabic"),
    tr("bulgarian"),
    tr("chinese"),
    tr("czech"),
    tr("danish"),
    tr("dutch"),
    tr("english_british"),
    tr("english_sdh"),
    tr("estonian"),
    tr("finnish"),
    tr("french"),
    tr("german"),
    tr("greek"),
    tr("hebrew"),
    tr("hungarian"),
    tr("italian"),
    tr("latvian"),
    tr("lithuanian"),
    tr("norwegian"),
    tr("polish"),
    tr("portuguese_brazilian"),
    tr("russian"),
    tr("slovak"),
    tr("slovene"),
    tr("spanish"),
    tr("spanish_latin_american"),
    tr("swedish"),
    tr("thai"),
  ];
}
